import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
  navy: "#263049",
  navyDark: "#1a2233",
  copper: "#b5651d",
  cream: "#faf7f2",
  border: "#e2ded6",
  text: "#1f2430",
  textSoft: "#5c6270",
};

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: COLORS.text,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  logo: { width: 140 },
  titleBlock: { alignItems: "flex-end" },
  h1: { fontSize: 18, fontFamily: "Helvetica-Bold", color: COLORS.navy },
  h2: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginTop: 16,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingBottom: 3,
  },
  metaText: { fontSize: 9, color: COLORS.textSoft },
  twoCol: { flexDirection: "row", justifyContent: "space-between", gap: 20 },
  col: { flex: 1 },
  label: { fontSize: 8, color: COLORS.textSoft, textTransform: "uppercase" },
  value: { fontSize: 10, marginBottom: 6 },
  table: { width: "100%" },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: COLORS.cream,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  th: { fontSize: 8, fontFamily: "Helvetica-Bold", color: COLORS.navy, textTransform: "uppercase" },
  td: { fontSize: 9 },
  colDescription: { flex: 3 },
  colQty: { flex: 1, textAlign: "right" },
  colPrice: { flex: 1.2, textAlign: "right" },
  colTotal: { flex: 1.2, textAlign: "right" },
  totalsBlock: { marginTop: 12, alignItems: "flex-end" },
  totalsRow: { flexDirection: "row", width: 220, justifyContent: "space-between", paddingVertical: 2 },
  totalsLabel: { fontSize: 9, color: COLORS.textSoft },
  totalsValue: { fontSize: 9 },
  totalsEmphasis: { fontSize: 11, fontFamily: "Helvetica-Bold", color: COLORS.navy },
  note: {
    marginTop: 12,
    padding: 8,
    backgroundColor: COLORS.cream,
    fontSize: 9,
    fontStyle: "italic",
    color: COLORS.textSoft,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 7,
    color: COLORS.textSoft,
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: COLORS.border,
    paddingTop: 6,
  },
});
